### HOME-MANAGER CONFIG

# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

fenv source /etc/profiles/per-user/julian/etc/profile.d/hm-session-vars.sh

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/julian/.local/share/fish/home-manager_generated_completions" $post
    end

end


### PERSONAL CONFIG FROM HERE DOWN

# Disable the fish greeting
set -U fish_greeting

# Configure new paths
set -gx PATH $HOME/.local/bin $PATH

# We know we will be using XDG_CONFIG_HOME, but MacOS may not
set -gx XDG_CONFIG_HOME $HOME/.config

# TODO: Load/unload mise upon entering/leaving a directory

# Set terminal colors appropriately
if set -q IS_NIXOS
	if test -z "$WAYLAND_DISPLAY" -a "$XDG_VTNR" -gt 0
		set -gx TERM vt100
	else
		set -gx TERM xterm-256color
	end

	# launch Hyprland if a session is not already active in VTNR 1
	if test -z "$WAYLAND_DISPLAY" -a "$XDG_VTNR" = 1
		exec uwsm start hyprland-uwsm.desktop
	end
end

# Carapace config
set -Ux CARAPACE_BRIDGES 'fish'
carapace _carapace | source

# Aliases
alias gg="lazygit"
alias t="tar -czf"
alias ls="eza" # we almost never want to use coreutils ls
alias cd="z" # we almost never want to use coreutils cd
