general {
    lock_cmd = sh -c "$HOME/dotfiles/nixos/niri/lock.sh"
    before_sleep_cmd = sh -c "$HOME/dotfiles/nixos/niri/display-off.sh"
    after_sleep_cmd = sh -c "$HOME/dotfiles/nixos/niri/display-on.sh"
    ignore_dbus_inhibit = false
}

listener {
    timeout = 240
    on-timeout = sh -c "$HOME/dotfiles/nixos/niri/display-off.sh"
    on-resume = sh -c "$HOME/dotfiles/nixos/niri/display-on.sh"
}
