# MacBook Pro hardware configuration
# This will be generated by nixos-generate-config after Asahi install
{ config, lib, pkgs, modulesPath, ... }:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  # TODO: Fill in after Asahi install
}
